name: Publish Olive Packages

on:
  push:
    branches: [ add-packages ]

jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Publish Olive NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive/Olive.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive ApiClient NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.ApiClient/Olive.ApiClient.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Audit NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Audit/Olive.Audit.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Audit DatabaseLogger NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Audit.DatabaseLogger/Olive.Audit.DatabaseLogger.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws/Olive.Aws.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      
    - name: Publish Olive Aws EventBus NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.EventBus/Olive.Aws.EventBus.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws LambdaFunction NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.LambdaFunction/Olive.Aws.LambdaFunction.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws Mvc NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.Mvc/Olive.Aws.Mvc.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws Ses NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.Ses/Olive.Aws.Ses.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws Ses AutoFetch NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.Ses.AutoFetch/Olive.Aws.Ses.AutoFetch.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws Ses AutoFetch TestConsole NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.Ses.AutoFetch.TestConsole/Olive.Aws.Ses.AutoFetch.TestConsole.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Aws Ses AutoFetch Tests NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Aws.Ses.AutoFetch.Tests/Olive.Aws.Ses.AutoFetch.Tests.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Azure NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Azure/Olive.Azure.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
    - name: Publish Olive Azure EventBus NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Azure.EventBus/Olive.Azure.EventBus.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Blob Aws NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Blob.Aws/Olive.Blob.Aws.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Blob Azure NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Blob.Azure/Olive.Blob.Azure.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Cloud NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Cloud/Olive.Cloud.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Compression NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Compression/Olive.Compression.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Console NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Console/Olive.Console.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive CSV NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.CSV/Olive.CSV.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Drawing NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Drawing/Olive.Drawing.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Email NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Email/Olive.Email.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Entities NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Entities/Olive.Entities.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Entities Data Replication NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Entities.Data.Replication/Olive.Entities.Data.Replication.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Olive Mvc NuGet Package
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Olive.Mvc/Olive.Mvc.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}